name: Take Screenshot with Puppeteer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  screenshot:
    name: Take Screenshot
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-14-large]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
    - name: Take screenshot with Chrome
      run: |
        npm ci
        node screenshot.mjs
    - name: Upload screenshot artifact
      uses: actions/upload-artifact@v4
      with:
        name: screenshot-${{ matrix.os }}
        path: screenshot.png
        if-no-files-found: error
